### ISSUE TITLE
cfdtx在圈上会一直报拿不到ck

### ISSUE THREAD

**Issue by sofs2005** [LucaLin233/QuantumultX-Personal-Configuration#1]
可以参考混沌大佬的修改，在111行修改：
$.cookieArr = [$.getdata("CookieJD") || "", $.getdata("CookieJD2") || "", ...CookiesJd].filter(x=>!!x);
另外我大概率报需要京喜环境，偶尔不报，这个是什么原因呢

**Comment by LucaLin233** [comment]
> 可以参考混沌大佬的修改，在111行修改：
> $.cookieArr = [$.getdata("CookieJD") || "", $.getdata("CookieJD2") || "", ...CookiesJd].filter(x=>!!x);
> 另外我大概率报需要京喜环境，偶尔不报，这个是什么原因呢

报拿不到ck大概是什么样子的，有没有截图？
然后你提供的这行是加到脚本里面么
我这里没有出现过报需要京喜ck过，还有待观察

**Comment by yyetss** [comment]
> > 可以参考混沌大佬的修改，在111行修改：
> > $.cookieArr = [$.getdata("CookieJD") || "", $.getdata("CookieJD2") || "", ...CookiesJd].filter(x=>!!x);
> > 另外我大概率报需要京喜环境，偶尔不报，这个是什么原因呢
> 
> 报拿不到ck大概是什么样子的，有没有截图？
> 然后你提供的这行是加到脚本里面么
> 我这里没有出现过报需要京喜ck过，还有待观察

提现信息不一致时啥情况啊
![IMG_D0CD30034852-1](https://user-images.githubusercontent.com/13871776/117239370-39d12280-ae61-11eb-82d0-a5e3551faa1b.jpeg)

**Comment by yyetss** [comment]
> > 可以参考混沌大佬的修改，在111行修改：
> > $.cookieArr = [$.getdata("CookieJD") || "", $.getdata("CookieJD2") || "", ...CookiesJd].filter(x=>!!x);
> > 另外我大概率报需要京喜环境，偶尔不报，这个是什么原因呢
> 
> 报拿不到ck大概是什么样子的，有没有截图？
> 然后你提供的这行是加到脚本里面么
> 我这里没有出现过报需要京喜ck过，还有待观察

提现信息不一致有解决办法嘛
![IMG_D0CD30034852-1](https://user-images.githubusercontent.com/13871776/117239522-84eb3580-ae61-11eb-82ef-5f3db4afd0ad.jpeg)

**Comment by LucaLin233** [comment]
> > > 可以参考混沌大佬的修改，在111行修改：
> > > $.cookieArr = [$.getdata("CookieJD") || "", $.getdata("CookieJD2") || "", ...CookiesJd].filter(x=>!!x);
> > > 另外我大概率报需要京喜环境，偶尔不报，这个是什么原因呢
> > 
> > 
> > 报拿不到ck大概是什么样子的，有没有截图？
> > 然后你提供的这行是加到脚本里面么
> > 我这里没有出现过报需要京喜ck过，还有待观察
> 
> 提现信息不一致有解决办法嘛
> ![IMG_D0CD30034852-1](https://user-images.githubusercontent.com/13871776/117239522-84eb3580-ae61-11eb-82ef-5f3db4afd0ad.jpeg)

是不是弄了多账号？我没出现过这个

**Comment by yyetss** [comment]
> > > 可以参考混沌大佬的修改，在111行修改：
> > > $.cookieArr = [$.getdata("CookieJD") || "", $.getdata("CookieJD2") || "", ...CookiesJd].filter(x=>!!x);
> > > 另外我大概率报需要京喜环境，偶尔不报，这个是什么原因呢
> > 
> > 
> > 报拿不到ck大概是什么样子的，有没有截图？
> > 然后你提供的这行是加到脚本里面么
> > 我这里没有出现过报需要京喜ck过，还有待观察
> 
> 提现信息不一致有解决办法嘛
> ![IMG_D0CD30034852-1](https://user-images.githubusercontent.com/13871776/117239522-84eb3580-ae61-11eb-82ef-5f3db4afd0ad.jpeg)



> > > > 可以参考混沌大佬的修改，在111行修改：
> > > > $.cookieArr = [$.getdata("CookieJD") || "", $.getdata("CookieJD2") || "", ...CookiesJd].filter(x=>!!x);
> > > > 另外我大概率报需要京喜环境，偶尔不报，这个是什么原因呢
> > > 
> > > 
> > > 报拿不到ck大概是什么样子的，有没有截图？
> > > 然后你提供的这行是加到脚本里面么
> > > 我这里没有出现过报需要京喜ck过，还有待观察
> > 
> > 
> > 提现信息不一致有解决办法嘛
> > ![IMG_D0CD30034852-1](https://user-images.githubusercontent.com/13871776/117239522-84eb3580-ae61-11eb-82ef-5f3db4afd0ad.jpeg)
> 
> 是不是弄了多账号？我没出现过这个

我试了单账号也是这样。一会现金池已空一会提现信息不一致

**Comment by LucaLin233** [comment]
> > > > 可以参考混沌大佬的修改，在111行修改：
> > > > $.cookieArr = [$.getdata("CookieJD") || "", $.getdata("CookieJD2") || "", ...CookiesJd].filter(x=>!!x);
> > > > 另外我大概率报需要京喜环境，偶尔不报，这个是什么原因呢
> > > 
> > > 
> > > 报拿不到ck大概是什么样子的，有没有截图？
> > > 然后你提供的这行是加到脚本里面么
> > > 我这里没有出现过报需要京喜ck过，还有待观察
> > 
> > 
> > 提现信息不一致有解决办法嘛
> > ![IMG_D0CD30034852-1](https://user-images.githubusercontent.com/13871776/117239522-84eb3580-ae61-11eb-82ef-5f3db4afd0ad.jpeg)
> 
> > > > > 可以参考混沌大佬的修改，在111行修改：
> > > > > $.cookieArr = [$.getdata("CookieJD") || "", $.getdata("CookieJD2") || "", ...CookiesJd].filter(x=>!!x);
> > > > > 另外我大概率报需要京喜环境，偶尔不报，这个是什么原因呢
> > > > 
> > > > 
> > > > 报拿不到ck大概是什么样子的，有没有截图？
> > > > 然后你提供的这行是加到脚本里面么
> > > > 我这里没有出现过报需要京喜ck过，还有待观察
> > > 
> > > 
> > > 提现信息不一致有解决办法嘛
> > > ![IMG_D0CD30034852-1](https://user-images.githubusercontent.com/13871776/117239522-84eb3580-ae61-11eb-82ef-5f3db4afd0ad.jpeg)
> > 
> > 
> > 是不是弄了多账号？我没出现过这个
> 
> 我试了单账号也是这样。一会现金池已空一会提现信息不一致

已空是正常的，现在肯定没得提了，京喜的账号是和京东的号一样的么？我这里一切正常，没出现过这种

**Comment by LucaLin233** [comment]
> > > > 可以参考混沌大佬的修改，在111行修改：
> > > > $.cookieArr = [$.getdata("CookieJD") || "", $.getdata("CookieJD2") || "", ...CookiesJd].filter(x=>!!x);
> > > > 另外我大概率报需要京喜环境，偶尔不报，这个是什么原因呢
> > > 
> > > 
> > > 报拿不到ck大概是什么样子的，有没有截图？
> > > 然后你提供的这行是加到脚本里面么
> > > 我这里没有出现过报需要京喜ck过，还有待观察
> > 
> > 
> > 提现信息不一致有解决办法嘛
> > ![IMG_D0CD30034852-1](https://user-images.githubusercontent.com/13871776/117239522-84eb3580-ae61-11eb-82ef-5f3db4afd0ad.jpeg)
> 
> > > > > 可以参考混沌大佬的修改，在111行修改：
> > > > > $.cookieArr = [$.getdata("CookieJD") || "", $.getdata("CookieJD2") || "", ...CookiesJd].filter(x=>!!x);
> > > > > 另外我大概率报需要京喜环境，偶尔不报，这个是什么原因呢
> > > > 
> > > > 
> > > > 报拿不到ck大概是什么样子的，有没有截图？
> > > > 然后你提供的这行是加到脚本里面么
> > > > 我这里没有出现过报需要京喜ck过，还有待观察
> > > 
> > > 
> > > 提现信息不一致有解决办法嘛
> > > ![IMG_D0CD30034852-1](https://user-images.githubusercontent.com/13871776/117239522-84eb3580-ae61-11eb-82ef-5f3db4afd0ad.jpeg)
> > 
> > 
> > 是不是弄了多账号？我没出现过这个
> 
> 我试了单账号也是这样。一会现金池已空一会提现信息不一致

信息不一致已修复
