### ISSUE TITLE
流媒体解锁检测Disney+失效

### ISSUE THREAD

**Issue by Rabbit-Spec** [LucaLin233/QuantumultX-Personal-Configuration#5]
节点解锁没问题，Disney+也可以正常用，但是解锁模块显示不支持。

**Comment by LucaLin233** [comment]
> 节点解锁没问题，Disney+也可以正常用，但是解锁模块显示不支持。

这个好像是解锁脚本的问题，qx那边shawn的脚本也检测不出，等待脚本作者更新看看，感谢反馈

**Comment by Rabbit-Spec** [comment]
好哒～坐等了～

**Comment by LucaLin233** [comment]
> 好哒～坐等了～

已经同步了佬的代码了，你现在再试试看呢

**Comment by Rabbit-Spec** [comment]
没问题了
